import type { Exercise } from "./types";

export const EXERCISE_LIBRARY: Exercise[] = [
  {
    id: "back-squat",
    name: "Barbell Back Squat",
    muscleGroup: "Quads, Glutes",
    equipment: "Barbell",
    difficulty: "intermediate",
    category: "legs",
    cues: ["Brace before descending", "Knees track over toes", "Drive through mid-foot"],
  },
  {
    id: "deadlift",
    name: "Conventional Deadlift",
    muscleGroup: "Hamstrings, Back",
    equipment: "Barbell",
    difficulty: "intermediate",
    category: "pull",
    cues: ["Bar over mid-foot", "Neutral spine throughout", "Push floor away, don't yank"],
  },
  {
    id: "bench-press",
    name: "Barbell Bench Press",
    muscleGroup: "Chest, Triceps",
    equipment: "Barbell",
    difficulty: "intermediate",
    category: "push",
    cues: ["Shoulder blades retracted", "Bar path over lower chest", "Elbows ~45deg from torso"],
  },
  {
    id: "ohp",
    name: "Overhead Press",
    muscleGroup: "Shoulders, Triceps",
    equipment: "Barbell",
    difficulty: "intermediate",
    category: "push",
    cues: ["Glutes and abs braced", "Bar path close to face", "Lock out overhead, not forward"],
  },
  {
    id: "pull-up",
    name: "Pull-Up",
    muscleGroup: "Lats, Biceps",
    equipment: "Pull-up bar",
    difficulty: "intermediate",
    category: "pull",
    cues: ["Full dead hang start", "Chest to bar", "Control the descent"],
  },
  {
    id: "push-up",
    name: "Push-Up",
    muscleGroup: "Chest, Triceps, Core",
    equipment: "Bodyweight",
    difficulty: "beginner",
    category: "push",
    cues: ["Straight line head to heels", "Elbows ~45deg", "Full range to chest near floor"],
  },
  {
    id: "goblet-squat",
    name: "Goblet Squat",
    muscleGroup: "Quads, Glutes",
    equipment: "Dumbbell",
    difficulty: "beginner",
    category: "legs",
    cues: ["Elbows inside knees at bottom", "Chest tall", "Sit down, not back"],
  },
  {
    id: "db-row",
    name: "Single-Arm Dumbbell Row",
    muscleGroup: "Lats, Upper back",
    equipment: "Dumbbell",
    difficulty: "beginner",
    category: "pull",
    cues: ["Flat back, hinge at hips", "Pull elbow to hip", "Avoid rotating torso"],
  },
  {
    id: "romanian-deadlift",
    name: "Romanian Deadlift",
    muscleGroup: "Hamstrings, Glutes",
    equipment: "Barbell",
    difficulty: "intermediate",
    category: "legs",
    cues: ["Soft knees, hinge at hips", "Bar stays close to legs", "Feel hamstring stretch, not lower back"],
  },
  {
    id: "lunge",
    name: "Walking Lunge",
    muscleGroup: "Quads, Glutes",
    equipment: "Dumbbell",
    difficulty: "beginner",
    category: "legs",
    cues: ["Torso upright", "Front knee tracks over foot", "Push through front heel"],
  },
  {
    id: "plank",
    name: "Plank",
    muscleGroup: "Core",
    equipment: "Bodyweight",
    difficulty: "beginner",
    category: "core",
    cues: ["Ribs pulled down", "Glutes squeezed", "Neutral neck, eyes to floor"],
  },
  {
    id: "hanging-leg-raise",
    name: "Hanging Leg Raise",
    muscleGroup: "Core",
    equipment: "Pull-up bar",
    difficulty: "advanced",
    category: "core",
    cues: ["Avoid swinging", "Curl pelvis, not just legs", "Controlled lower"],
  },
  {
    id: "kb-swing",
    name: "Kettlebell Swing",
    muscleGroup: "Glutes, Hamstrings, Cardio",
    equipment: "Kettlebell",
    difficulty: "beginner",
    category: "cardio",
    cues: ["Hip hinge, not a squat", "Snap hips at top", "Arms are just along for the ride"],
  },
  {
    id: "burpee",
    name: "Burpee",
    muscleGroup: "Full Body, Cardio",
    equipment: "Bodyweight",
    difficulty: "beginner",
    category: "cardio",
    cues: ["Chest to floor on push-up", "Explode into the jump", "Land soft"],
  },
  {
    id: "farmers-carry",
    name: "Farmer's Carry",
    muscleGroup: "Grip, Core, Full Body",
    equipment: "Dumbbell",
    difficulty: "beginner",
    category: "full_body",
    cues: ["Tall posture", "Shoulders down and back", "Short, controlled steps"],
  },
  {
    id: "dip",
    name: "Parallel Bar Dip",
    muscleGroup: "Chest, Triceps",
    equipment: "Dip bars",
    difficulty: "intermediate",
    category: "push",
    cues: ["Slight forward lean for chest", "Elbows track back, not flared wide", "Full lockout at top"],
  },
  {
    id: "face-pull",
    name: "Cable Face Pull",
    muscleGroup: "Rear delts, Upper back",
    equipment: "Cable",
    difficulty: "beginner",
    category: "pull",
    cues: ["Pull to eye level", "Externally rotate at end range", "Slow eccentric"],
  },
  {
    id: "bulgarian-split-squat",
    name: "Bulgarian Split Squat",
    muscleGroup: "Quads, Glutes",
    equipment: "Dumbbell",
    difficulty: "advanced",
    category: "legs",
    cues: ["Rear foot elevated, laces down", "Front shin stays vertical-ish", "Drive through front heel"],
  },
  {
    id: "ab-wheel",
    name: "Ab Wheel Rollout",
    muscleGroup: "Core",
    equipment: "Ab wheel",
    difficulty: "advanced",
    category: "core",
    cues: ["Brace before rolling out", "Avoid sagging hips", "Roll out only as far as control allows"],
  },
  {
    id: "incline-db-press",
    name: "Incline Dumbbell Press",
    muscleGroup: "Upper chest, Shoulders",
    equipment: "Dumbbell",
    difficulty: "beginner",
    category: "push",
    cues: ["30-45deg bench angle", "Press up and slightly in", "Control the stretch at bottom"],
  },
];

export const MUSCLE_GROUPS = Array.from(new Set(EXERCISE_LIBRARY.map((e) => e.muscleGroup)));
export const EQUIPMENT_TYPES = Array.from(new Set(EXERCISE_LIBRARY.map((e) => e.equipment)));
